name: simple_frame_app
description: "Flutter and Lua quickstart app scaffolding and standard library functions for Brilliant Frame development on Android/iOS"
version: 6.0.3
homepage:
repository: https://github.com/CitizenOneX/simple_frame_app

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  image: ^4.2.0
  logging: ^1.2.0
  frame_msg: ^1.0.1
  frame_ble: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
